### ISSUE TITLE
Нельзя поменять название канала

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#10]
**Описание**
После добавления канала в Telepost, его название не обновляется после изменения в Телеграм.

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем канал
2. Добавляем канал в Telepost (через веб-интерфейс или бота)
3. Меняем название канала в Телеграме
4. Видим, что название канала не обновляется в списке каналов Telepost в веб-интерфейсе и боте

**Ожидаемое поведение**
После изменения названия канала в списке каналов в Telepost название также должно обновиться, либо для этого должна быть какая-то кнопка.

**Скриншоты**
Добавил канал `Laboratory`, поменял его на `Laboratory1` — в веб-интерфейсе в списке название старое:
![image](https://user-images.githubusercontent.com/24430718/104635538-15371c00-56b3-11eb-8c43-0c6e796a0172.png)

Хотя в настройках канала видно, что Telepost новую инфу подтянул:
![image](https://user-images.githubusercontent.com/24430718/104635390-df923300-56b2-11eb-8593-b2ed50bd58a1.png)

В боте — тоже самое:
![image](https://user-images.githubusercontent.com/24430718/104635690-53ccd680-56b3-11eb-9102-3324651dc552.png)

**Важные детали:**
 - Тип поста: любой
 - Операционная система: любая
 - Браузер и его версия: любой

**Дополнительно**
Ссылка на обсуждение: https://t.me/c/1306965784/18728

**Comment by telepost-support** [comment]
Если изменить в телеграм то обновится до 2х часов.
Если изменить через телепост обновится сразу, исправил.

**Comment by nikolaev-rd** [comment]
В веб-версии наверху еще остается артефакт не переименованный:

![image](https://user-images.githubusercontent.com/24430718/108555459-8b5c1d80-7306-11eb-8595-c308ecf6dc53.png)

**Comment by nikolaev-rd** [comment]
Хотя принудительное обновление страницы (CMD+R / CTRL+R) — помогает.
