### ISSUE TITLE
Сломалось форматирование подтверждения от бота

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#100]
### Описание

После создания поста через бота уведомление начало приходить примерно в таком виде:
```
✅ Отложенный пост в канал <b>Антилень | Мотивация</b> создан и будет опубликован

<b>20 октября 2022 г., 17:00 GMT+3</b> Europe/Moscow
```

Видно, что вылезло HTML-форматирование, вместо того, чтобы текст был выделен **жирным**.

### Как повторить

Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост любого типа через бота
2. Откладываем пост на любое время
3. Видим ответ от бота о том, что пост успешно отложен, но форматирование такого уведомления сломано

### Ожидаемое поведение

Раньше такого не было, и буквально 13.10.2022 сломалось. Ожидается, что форматирование должно работать как раньше.

### Тип поста

Текст, Фото, Видео, Документ, Альбом, Опрос, Музыка, Голос, Анимация

### В каком интерфейсе воспроизводится баг?

Бот

### Операционная система

iOS, Android

### Ссылки на обсуждение

* <https://t.me/c/1306965784/47343>
* <https://t.me/c/1306965784/49271>

**Comment by telepost-support** [comment]
Пофикшено
