### ISSUE TITLE
Бот теряет нативное форматирование текста в альбоме

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#106]
### Описание

При создании поста с альбомом бот "теряет" нативное форматирование текста.

![telegram-cloud-photo-size-2-5224468910177371396-y](https://user-images.githubusercontent.com/24430718/206560145-5d500123-12be-4616-af1e-f3973c8e3599.jpg)

### Как повторить

Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост с типом "Альбом"
2. Загружаем в него несколько картинок (объединяем как альбом)
3. Делаем описание альбома: текст с любым форматированием, например с **жирным** текстом
4. Видим, что бот "теряет" форматирование

### Ожидаемое поведение

Бот должен поддерживать нативное форматирование текста для описания альбома (в настройках бота выставлено: Native).

### Тип поста

Альбом

### В каком интерфейсе воспроизводится баг?

Бот

### Браузер

Другой

### Операционная система

iOS

### Ссылки на обсуждение

* <https://t.me/c/1306965784/48685>

**Comment by telepost-support** [comment]
Пофикшено
