### ISSUE TITLE
Добавление реакций при выборе "альбома" - несколько фото

### ISSUE THREAD

**Issue by Keffman** [Telepost-me/support#107]
### Краткое описание

Хотелось бы добавить реакции в пост, когда выгружаем в 1 сообщении несколько фотографий

### Как вы видите решение/реализацию

Прикрепить реакции в веб вебрсии. Скрин
![image](https://user-images.githubusercontent.com/123264710/213881110-99cb1606-3efe-4aa6-8ccd-9246877f30c6.png)

### Альтернативные варианты

—

### Ссылки на обсуждение

* <https://t.me/c/1306965784/49745>

**Comment by nikolaev-rd** [comment]
В боте кнопки реакции через `::/::` также не добавляются.

**Comment by nikolaev-rd** [comment]
В бот API нет возможности добавлять кнопки под альбомным постом, вот и реакций не будет https://core.telegram.org/bots/api#sendmediagroup
