### ISSUE TITLE
Не работают реакции под Фото в мульти-публикации

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#12]
**Описание**
Реакции не работают, когда одновременно происходит публикация следующего контента: Текст + Фото + Реакции + Гифка. 

Ошибка: 
```
can't find reactions
```

Если из контента убрать гифку, все реакции начинают работать.

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост сразу с несколькими типами публикаций:
    - Текст
    - Фото с реакциями
    - Анимация (в формате mp4)
2. Постим в канал / бота
3. Нажимаем на реакцию и видим ошибку

**Ожидаемое поведение**
Реакции под фото должны работать даже в такой мульти-публикации.

**Скриншоты**
Мульти-публикация и ошибка при нажатии на реакции:
![image](https://user-images.githubusercontent.com/24430718/104856040-3bfa8a00-5921-11eb-906b-672f34eef67d.png)

**Важные детали:**
 - Тип поста:
    * Текст
    * Фото
    * Анимация
 - Операционная система: любая
 - Браузер и его версия: любая
 - Версия Telepost-web:  v2.2.1-16f16406

**Дополнительно**
Гифки + Реакции работают без проблем, однако стоит добавить фото к данному букету — реакции перестают работать.

Ссылка на обсуждение: https://t.me/c/1306965784/18796

**Comment by telepost-support** [comment]
Нужно проверить еще раз, попытался воспроизвести не получилось.

**Comment by nikolaev-rd** [comment]
[Проверил](https://t.me/laboratory_ch/115): действительно, сейчас бага уже не воспроизводится.
