### ISSUE TITLE
Съехали эмодзи

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#16]
**Описание**
В окне выбора эмодзи они съехали относительно категорий:
![image](https://user-images.githubusercontent.com/24430718/107274066-00a33500-6a61-11eb-9452-de4fc827742e.png) ![image](https://user-images.githubusercontent.com/24430718/107274072-04cf5280-6a61-11eb-8145-831c264ee1f9.png)

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост, например, с типом "Текст"
2. Открываем диалог с эмодзи
3. Видим, что эмодзи съехали

**Ожидаемое поведение**
При переключении категорий эмодзи должны соответствовать выбранной категории.

**Важные детали:**
 - Тип поста:
    * Текст
    * Фото
    * Видео
    * Документ
    * Альбом
    * Опрос
    * Музыка
    * Голос
    * Анимация
 - Операционная система: Windows, MacOS
 - Браузер и его версия: любой
 - Версия Telepost (web):  v2.2.1-16f16406

**Дополнительно**
Обсуждение:
* https://t.me/c/1306965784/19654
* https://t.me/c/1306965784/19663

**Comment by telepost-support** [comment]
На дев уже пофиксил https://app.dev.telepost.pw/

**Comment by nikolaev-rd** [comment]
Подтверждаю, все ОК:
![image](https://user-images.githubusercontent.com/24430718/126551320-ba12ddad-313c-4013-8ec8-b53605d85106.png)

![image](https://user-images.githubusercontent.com/24430718/126551372-99f599aa-3416-490b-b948-2a911a7a72b6.png)

**Comment by nikolaev-rd** [comment]
Починилось на проде (версия v2.4.4-470d9ca4), но потребовалось почистить кеш:

![image](https://user-images.githubusercontent.com/24430718/128084622-0801ad58-d436-46ce-844f-17469addb07c.png)

![image](https://user-images.githubusercontent.com/24430718/128084464-80879e90-46a4-4375-a3eb-453d97e18c22.png)
