### ISSUE TITLE
Нельзя добавить ссылку на ботов в тексте поста

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#27]
**Описание**
При добавлении ссылки на ботов в тексте поста, ссылка пропадает в публикации. При этом эта же ссылка в кнопке-ссылке работает нормально (работа кнопок-ссылок исправлялась в issue #8).

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост любого типа, где можно добавить текст и обернуть его ссылкой
2. Выделяем текст и вставляем ссылку вида: `tg://resolve?start=ZGw6MzAwNjg&domain=pkrmng_bot`
3. Пробуем сохранить
4. Делаем предпросмотр в бота и там только текст без ссылки
5. В превью ссылки в посте при этом такое:
   ![image](https://user-images.githubusercontent.com/24430718/115120249-36125480-9fb5-11eb-889c-49ecff59ca6d.png)

**Ожидаемое поведение**
Ссылки на ботов должны работать в тексте постов, а не только в кнопках.

**Важные детали:**
 - Тип поста:
    * Текст
 - Операционная система: любая
 - Браузер и его версия: любой
 - Версия Telepost (web):  v2.3.1-1afc47ad

**Дополнительно**
Ссылка на обсуждение: https://t.me/c/1306965784/22824

**Comment by telepost-support** [comment]
На дев уже пофиксил https://app.dev.telepost.pw/

**Comment by nikolaev-rd** [comment]
Да, [теперь все норм](https://t.me/laboratory_ch/118) (версия v2.3.1-2cfac7a7):

![image](https://user-images.githubusercontent.com/24430718/126553892-4ffc6c9d-1af0-4048-9565-835c69ba0e74.png)

![image](https://user-images.githubusercontent.com/24430718/126553979-5a1d6b96-ba44-48f9-b7fc-5f369108060d.png)

**Comment by nikolaev-rd** [comment]
Перестало воспроизводиться на проде: v2.4.4-470d9ca4.
