### ISSUE TITLE
Несколько документов в одном посте

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#32]
**Краткое описание**
Сейчас через веб-версию/бота нельзя добавить несколько документов (файлов) в одном посте.

В веб-версии диалог дает возможность загрузить только один файл:
![image](https://user-images.githubusercontent.com/24430718/117552369-92681180-b053-11eb-8bd9-4df7f65d79ea.png)

В боте можно закинуть несколько файлов, которые распознаются как альбом, но в итоге не дает опубликовать:
![image](https://user-images.githubusercontent.com/24430718/117552423-d6f3ad00-b053-11eb-8ea9-ccf22150d002.png)

При этом в стандартном клиенте Телеграма можно сделать такой пост (на скриншоте видно, что два файла в одном сообщении, а не в отдельных):
![image](https://user-images.githubusercontent.com/24430718/117552463-1fab6600-b054-11eb-8d64-a55116479dc3.png)

**Как вы видите решение/реализацию**
В диалоге создания поста с типом "Документ" можно добавить несколько файлов. Важно сразу проверяется все необходимые лимиты (кол-во файлов, размер). Также это можно поддержать в боте.

**Альтернативные варианты**
—

**Дополнительно**
Ссылка на обсуждение: https://t.me/c/1306965784/23399

**Comment by telepost-support** [comment]
Будет в 2.5 через альбом, уже можно создавать на дев через бот

**Comment by nikolaev-rd** [comment]
[Работает](https://t.me/laboratory_ch/156) на проде как ожидается:
![image](https://user-images.githubusercontent.com/24430718/130334822-adbba496-518f-401c-9ba7-f9d47826b294.png)
