### ISSUE TITLE
Поддержка аудио-файлов в альбоме

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#38]
**Краткое описание**
В посте с типом "Альбом" сейчас поддерживаются только файлы с типами: jpeg, png, mp4, mov. Но в Телеграме в родных клиентах уже давно есть поддержка альбомов для аудио (как минимум mp3).

**Как вы видите решение/реализацию**
Необходимо добавить поддержку аудио-файлов в пост с типом "Альбом", чтобы можно было опубликовать одним постом:
![image](https://user-images.githubusercontent.com/24430718/120084155-ae048c00-c0d6-11eb-8910-664231ca12ac.png)

**Альтернативные варианты**
Такой вариант уже есть: как [описано в блоге](https://t.me/telepost_blog/18), можно сделать мультипубликацию из аудио-файлов (максимум 5 файлов), клиент Телеграм позволяет затем прослушивать аудио в режиме альбома (на самом деле это отдельные посты, которые визуально объединяются в альбом только при прослушивании). 

![image](https://user-images.githubusercontent.com/24430718/120084270-75b17d80-c0d7-11eb-9548-e167f94fcb97.png)

![image](https://user-images.githubusercontent.com/24430718/120084262-65999e00-c0d7-11eb-8cbb-997811b9b9d3.png)

Но это, конечно, всё не то — хочется именно одним постом

**Дополнительно**
Ссылка на обсуждение: <https://t.me/c/1306965784/23740>

**Comment by telepost-support** [comment]
Будет в 2.5, через бот можно уже создавать на дев

**Comment by nikolaev-rd** [comment]
Ограничение на размер файла — также 5 МБ? Пробую на проде [пост опубликовать](https://app.telepost.me/sp/612020ad7ae8d9cd4da9c5db/7aah7uzm3), но вылезает ошибка:

![image](https://user-images.githubusercontent.com/24430718/130296005-c0b49e51-aa2e-4dc3-9c4a-1f58b8580c13.png)

**Comment by telepost-support** [comment]
Думаю есть ограничение на суммарный размер запроса на создание альбома. 
В документации ничего не упоминается https://core.telegram.org/bots/api#sendmediagroup

Если загрузить 10 файлов и сделать предпосмотр в бот тогда будет ошибка 413 так как все файлы будут отправляться одним запросом.

Если создать альбом из 5ти файлов сделать предпросмотр эти 5 файлов закешируються и дальше при публикации через тот же бот будет использоваться ид файла на сервере телеграм. Потом добавляем еще 5 файлов и делаем предпросмотр, тогда в бот должно прийти все 10 файлов.

Потестил, думаю 50 мб лимит. Чтобы обойти только запускать свой инстанс https://github.com/tdlib/telegram-bot-api.

**Comment by nikolaev-rd** [comment]
У меня в предпросмотр пролезло около 80 МБ (8 файлов):
![image](https://user-images.githubusercontent.com/24430718/130322594-41d05695-27f7-4cbd-9a9d-5477db71b517.png)

А вот [запостить](https://t.me/laboratory_ch/154) удалось только 5 файлов (суммарно как раз около 50 МБ).

Думаю, надо про эти лимиты обязательно в веб-интерфейсе и боте написать, а то у пользавателей постоянно будет вопрос про это. Со своей стороны могу в [FAQ](https://telepost-me.github.io) добавить, но его (мягко говоря) не всегда читают.

**Comment by nikolaev-rd** [comment]
Сделал инструкцию: https://telepost-me.github.io/faq/post-audio-album/
