### ISSUE TITLE
Не работают кнопки бота на английской локализации

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#40]
**Описание**
В случае, когда используется английский язык (в веб-интерфейсе, настройках Телеграм-клиента:, а также ОС) — кнопки в боте имеют косяки + некоторые не работают.

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост любого типа в боте
2. Доходим до шага добавления url-кнопок
3. Видим такое:
   ![telegram-cloud-photo-size-2-5192667275805701018-m](https://user-images.githubusercontent.com/24430718/127392230-b06fde3a-2de3-463a-950b-5c72b9e4f7d6.jpg)
4. При нажатии кнопки бота не работают.

**Ожидаемое поведение**
Кнопки должны работать при использовании английской локализации, тем более что на русской локализации точно все работает.

**Дополнительно**
Баг воспроизводится на Android:

https://user-images.githubusercontent.com/24430718/127399418-33f395a8-a453-4d23-a79d-b387dca3c102.mp4

**Важные детали:**
 - Тип поста: любой
 - Операционная система: Windows, Android
 - Версия Telepost (web): v2.4.4-470d9ca4

**Дополнительно**
Ссылки на обсуждение:
* https://t.me/c/1306965784/26531
* https://t.me/c/1306965784/26597

**Comment by telepost-support** [comment]
Уже пофиксешо

**Comment by nikolaev-rd** [comment]
Пользаки подтверждают: https://t.me/c/1306965784/26699
