### ISSUE TITLE
Возможность удаляться из редакторов

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#41]
**Краткое описание**
После добавления пользователя в редакторы, канал нельзя удалить из списка каналов. Сейчас редактора из канала может удалить только администратор канала.

**Как вы видите решение/реализацию**
Пользователь после того, как его добавили в редакторы, может самостоятельно удалить канал из списка, тем самым он автоматически удалится из редакторов канала.

**Дополнительно**
Ссылка на обсуждение: <https://t.me/c/1306965784/26655>

**Comment by telepost-support** [comment]
Уже есть на дев

**Comment by nikolaev-rd** [comment]
Работает на проде.
Еще можно поправить заголовок: сделать "Удалить себя **из** редакторов"

![image](https://user-images.githubusercontent.com/24430718/131264535-3162dc60-2f97-4b0e-8a05-360b4dfde49e.png)
