### ISSUE TITLE
Слетает закреп в повторах поста

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#42]
**Описание**
При создании публикации с повтором с включенным закрепом поста, в следующих повторах публикации закреп слетает. Если включить закреп в след. посте-повторе — пост опубликуется с закрепом. Но снова слетит для след. поста-повтора.

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост любого типа, настраиваем повтор поста (любой интервал), включаем закреп в настройках поста
2. Публикуем пост
3. Видим, что создались посты-повторы в календаре, в которых закреп отключен
4. Включаем закреп в будущем посте-повторе
5. Видим, что после ручного включения закрепа, пост-повтор публикуется с закрепом
6. Когда дело доходит до очередного поста-повтора, видим что настройка закрепа снова отключена — оставляем как есть
6. Видим, что пост выходит без закрепа

**Ожидаемое поведение**
Посты-повторы должны также закреплятся, как и исходный пост.

**Скриншоты**
Ниже — настройка [поста-повтора](https://t.me/laboratory_ch/122), [исходный пост](https://t.me/laboratory_ch/120) которого был с включенным закрепом.
![image](https://user-images.githubusercontent.com/24430718/128602996-27d526bb-45a4-4d24-8dc5-2ac380baa6ee.png)

[Пост-повтор, где настройка закрепа не была включена вручную](https://t.me/laboratory_ch/125) — опубликовался без закрепа.

**Важные детали:**
 - Тип поста: любой
 - Операционная система: любая
 - Браузер и его версия: любой
 - Версия Telepost (web): v2.4.4-470d9ca4

**Дополнительно**
Ссылка на обсуждение: https://t.me/c/1306965784/27209

**Comment by telepost-support** [comment]
Уже есть на дев

**Comment by nikolaev-rd** [comment]
[Проверил](https://t.me/laboratory_ch/133): бага починилась на dev.

**Comment by nikolaev-rd** [comment]
[Работает](https://t.me/laboratory_ch/144) на версии v2.5.0-f2b2186e
