### ISSUE TITLE
Видео в формате mv4 постится как файл

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#43]
**Описание**
При создании видео-поста в формате m4v через веб-интерфейс, пост выходит как файл.

**Как повторить**
Шаги, с помощью которых можно воспроизвести баг:
1. Создаем пост с типом "Видео"
2. Загружаем видео в формате m4v (например: [video.m4v.zip](https://github.com/Telepost-me/support/files/6957623/video.m4v.zip))
3. В редакторе поста все выглядит нормально (есть превью видео), и даже предлагается поменять обложку.
4. Публикуем пост и видим, что он вышел в как файл: https://t.me/laboratory_ch/127
5. Для проверки конвертируем это же видео в mp4, повторяем шаги 1-4 и видим, что пост публикуется нормально (как видео с превью): https://t.me/laboratory_ch/128

**Ожидаемое поведение**
Утверждается, что раньше этот тип видео поддерживался и публиковался нормально. Соответственно ожидается, что раз нет ошибок про формат видео, пост должен публиковаться как видео.

**Скриншоты**
Два тестовых поста из описания выше:
![image](https://user-images.githubusercontent.com/24430718/128779663-5a577d81-9cd9-4495-8213-2b97ea4a18de.png)

**Важные детали:**
 - Тип поста:
    * Видео
 - Операционная система: любая
 - Браузер и его версия: любой
 - Версия Telepost (web): v2.4.4-470d9ca4

**Дополнительно**
Ссылка на обсуждение: https://t.me/c/1306965784/27367

**Comment by telepost-support** [comment]
Переименовать файл поможет `Экхарт_Толле_Жизнь_Говорит_Проснись.m4v` --> `Экхарт_Толле_Жизнь_Говорит_Проснись.mp4`

`m4v` отображается в телепост и публикуется как видео, бот апи когда видит `m4v` публикует как документ.

в версии 2.5 будет автоматом переименовываться  .m4v -> .mp4

**Comment by nikolaev-rd** [comment]
[Проверил](https://t.me/laboratory_ch/146), бага больше не воспроизводится на версии v2.5.0-f2b2186e.
