### ISSUE TITLE
Добавить поддержку скрытого текста — spoiler

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#81]
### Краткое описание

В Телеграм завезли [скрытый текст (spoiler)](https://telegram.org/blog/reactions-spoilers-translations/ru#skritii-tekst). Хотелось бы иметь такое же в Телепосте при форматировании постов.

P.S. В Bot API это также [добавили](https://core.telegram.org/bots/api#december-30-2021) (30 декабря 2021 года).

### Как вы видите решение/реализацию

Добавить новый пункт в меню, которое появляется при выделении текста:

![image](https://user-images.githubusercontent.com/24430718/150138527-82a0a7db-e2a3-4926-afc5-f44bf4a79048.png)

### Альтернативные варианты

Поддержка spoiler при создании поста через бота.

### Ссылки на обсуждение

* <https://t.me/c/1306965784/36380>
* <https://t.me/c/1306965784/37132>
* <https://t.me/c/1306965784/37810>
* <https://t.me/c/1306965784/37885>
* <https://t.me/c/1306965784/38518>
* <https://t.me/c/1306965784/38933>
* <https://t.me/c/1306965784/42156>
* <https://t.me/c/1306965784/45915>
* <https://t.me/c/1306965784/49339>

**Comment by nikolaev-rd** [comment]
Тестируется на dev (добавление спойлера через бота в режиме Native):
![telegram-cloud-photo-size-2-5451875028929988315-x](https://user-images.githubusercontent.com/24430718/220460409-b262199e-5298-45b4-8088-29784645e4a8.jpg)

**Comment by telepost-support** [comment]
Уже на проде
