### ISSUE TITLE
Ошибка при удалении подписи к картинке

### ISSUE THREAD

**Issue by nikolaev-rd** [Telepost-me/support#92]
### Описание

В боте при попытке убрать подпись у поста с картинкой — вылетает ошибка, описание в итоге не убирается.

### Как повторить

Шаги, с помощью которых можно воспроизвести баг:
1. Загружаем через бота любую картинку с подписью (получается пост с типом "Фото")
2. Пытаемся отредактировать пост в боте, убрав подпись к картинке
3. Видим ошибку: `Cannot read property 'split' of undefined`
   ![telegram-cloud-photo-size-2-5229198463739216109-y](https://user-images.githubusercontent.com/24430718/170839758-0f46e1b8-1b45-4f72-8e14-bbe5753c0cbf.jpg)

Обходные решения:
* Пересоздать пост с картинкой сразу без подписи
* Сохранить как черновик и отредактировать в веб-версии Телепоста

### Ожидаемое поведение

Удаление подписи должно работать в боте, и не должно вызывать ошибку.

### Тип поста

Фото

### В каком интерфейсе воспроизводится баг?

Бот

### Операционная система

iOS, Android

### Ссылки на обсуждение

* <https://t.me/c/1306965784/42788>

**Comment by telepost-support** [comment]
Пофикшено
